version: '3.9'
services:
  backend:
    image: adredback
    restart: always
    env_file: env/.env.prod
    build: ./
    ports:
      - 3000:3000
    command: gunicorn --worker-class gevent --bind 0.0.0.0:3000 wsgi:app --log-level debug
    volumes:
      - $HOME/.aws/credentials:/root/.aws/credentials:ro

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
